version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: container_mysql
    restart: always
    volumes:
      - first-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - first-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    
  apinode:
    build:
      context: .
    container_name: container_apinode
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - first-network
    
networks: 
  first-network:
    driver: bridge
volumes:
  first-volume:
